### PR TITLE
Telemetry: Lvm exporter for Prometheus 

### PR DESCRIPTION
**Pull request by NajmudheenCT**
**What this PR does / why we need it**:
This PR is  the  first version of lvm exporter for Prometheus .
lvm exporter creates and http end point for Prometheus/third party to scrape/consume metrics.This uses openSDS lvm metric driver code to collect metrics and expose an endpoint .
This is an independent   binary  where user has to provide the port number for endpoint as command line parameter.
This  port number can be configured in Prometheus config to scrape from  lvm_exporter .

**Which issue this PR fixes** 

**Special notes for your reviewer**:
This has dependency with https://github.com/opensds/opensds/pull/668 for the driver code 
and https://github.com/opensds/opensds/pull/660 for the Prometheus libraries 
**Release note**:

### CODE REVIEW

**Comment by NajmudheenCT** [comment]
@xing-yang @leonwanghui @kumarashit @skdwriting @rhsakarpos @wisererik

**Comment by rhsakarpos** [comment]
Please refer to this as example, to add thread safety and configuration for LVM exporter (Prometheus needs the exporter to be thread safe too)

https://github.com/digitalocean/ceph_exporter/blob/luminous/exporter.go

**Comment by NajmudheenCT** [comment]
> @NajmudheenCT Please refer to this as example, to add thread safety and configuration for LVM exporter (Prometheus needs the exporter to be thread safe too)
> 
> https://github.com/digitalocean/ceph_exporter/blob/luminous/exporter.go

Thank you! . I have implemented  mutex lock and unlock to collect method

**Comment by leonwanghui** [comment]
I'm wondering why there are so many files added, did you use `dep ensure` to install them?

**Comment by NajmudheenCT** [comment]
> I'm wondering why there are so many files added, did you use `dep ensure` to install them?

@leonwanghui , Yes, dep ensure has been run and it added all dependency packages to /vendor

**Comment by leonwanghui** [comment]
> @leonwanghui , Yes, dep ensure has been run and it added all dependency packages to /vendor

But I didn't see any changes on `Gopkg.toml`, maybe you should update that file first before running `dep ensure`

**Comment by NajmudheenCT** [comment]
@leonwanghui , 
I ran dep init and dep ensure again to update the packages, I hope this operation has created so many copied files. I am closing this PR and opened a new PR https://github.com/opensds/opensds/pull/697

**Pull request closed without merging**
