### PR TITLE
Handle volume in batch

### LINKED ISSUE #1153: Failed to create more than one volume in a batch
**Is this a BUG REPORT or FEATURE REQUEST?**:

 /kind bug

**What happened**:
Failed to create more than one volume in a batch.
Some volumes get error status.

**What you expected to happen**:
Volumes should be able to create in a batch.

**How to reproduce it (as minimally and precisely as possible)**:
Run multi "osdsctl create volume 1 --name=test" at once, or create multi pvc in a single yaml file.
Then check the status by "osdsctl volume list" or "kubectl get pvc"

**Anything else we need to know?**:
Root cause:
in pkg/dock/client/client.go
```
func (c *DockClient) Connect(edp string) error {
	// Set up a connection to the Dock server.
	conn, err := grpc.Dial(edp, grpc.WithInsecure())
	if err != nil {
		log.Errorf("did not connect: %+v\n", err)
		return err
	}
	// Create dock client via the connection.
	c.FileShareDockClient = pb.NewFileShareDockClient(conn)
	c.ProvisionDockClient = pb.NewProvisionDockClient(conn)
	c.AttachDockClient = pb.NewAttachDockClient(conn)
	/****************Root Cause******************/
	/* conn was saved to c.ClientConn */
	/* For example, if we have two request, we will have two conn, and c.ClientConn always saved the last one*/
	/* When we want to close the first conn, we call DockClient.Close, whiech call c.ClientConn.Close, which would close the second one*/
	c.ClientConn = conn

	return nil
}

func (c *DockClient) Close() {
	c.ClientConn.Close()
}
```

**Environment**:
- Hotpot(release/branch) version: latest
- OS (e.g. from /etc/os-release): Oracle Linux 7.7
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

### PR DESCRIPTION
**Pull request by ThisIsClark**
**What this PR does / why we need it**:
Keep GRPC connection alive so we can create/delete/attach/detach volumes in a batch, otherwise GRPC connection would be closed unexpectedly.
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #1153 

**Special notes for your reviewer**:

**Release note**:

```release-note
[root@master-node block]# kubectl create -f multi-pvc.yaml
storageclass.storage.k8s.io/csi-sc-opensdsplugin-block created
persistentvolumeclaim/csi-pvc-opensdsplugin-block1 created
persistentvolumeclaim/csi-pvc-opensdsplugin-block2 created
persistentvolumeclaim/csi-pvc-opensdsplugin-block3 created
persistentvolumeclaim/csi-pvc-opensdsplugin-block4 created
persistentvolumeclaim/csi-pvc-opensdsplugin-block5 created
persistentvolumeclaim/csi-pvc-opensdsplugin-block6 created
[root@master-node block]# kubectl get pvc
NAME                           STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS                 AGE
csi-pvc-opensdsplugin-block1   Bound    pvc-442b20f3-3112-4b7a-9f72-24cf0306c744   1Gi        RWX            csi-sc-opensdsplugin-block   6s
csi-pvc-opensdsplugin-block2   Bound    pvc-7e5eff69-6694-4dba-b659-1f22adcbbf83   1Gi        RWX            csi-sc-opensdsplugin-block   6s
csi-pvc-opensdsplugin-block3   Bound    pvc-c6251101-94df-44ce-b755-b3ab6b635185   1Gi        RWX            csi-sc-opensdsplugin-block   6s
csi-pvc-opensdsplugin-block4   Bound    pvc-0029811b-a4cb-44af-ae8c-4f3bb81f760b   1Gi        RWX            csi-sc-opensdsplugin-block   6s
csi-pvc-opensdsplugin-block5   Bound    pvc-c1e37c41-0808-43db-a5c7-b9374602b29c   1Gi        RWX            csi-sc-opensdsplugin-block   6s
csi-pvc-opensdsplugin-block6   Bound    pvc-0263ef00-7a3c-4c1e-9fce-33c97f9b5738   1Gi        RWX            csi-sc-opensdsplugin-block   6s
[root@master-node opensds]# osdsctl volume list
+--------------------------------------+------------------------------------------+-------------+------+------------------+-----------+--------------------------------------+
| Id                                   | Name                                     | Description | Size | AvailabilityZone | Status    | ProfileId                            |
+--------------------------------------+------------------------------------------+-------------+------+------------------+-----------+--------------------------------------+
| dc8cd1bb-bff7-4fb2-911d-d50c77399129 | pvc-442b20f3-3112-4b7a-9f72-24cf0306c744 |             | 1    | default          | available | 85bf0d5b-f0ed-4573-ac1d-a21d61402bf9 |
| d6f4299b-19a4-46f9-b708-d5c6e641b4c0 | pvc-0263ef00-7a3c-4c1e-9fce-33c97f9b5738 |             | 1    | default          | available | 85bf0d5b-f0ed-4573-ac1d-a21d61402bf9 |
| 43ce6a63-7aa1-4b51-9de5-f793b90e07f0 | pvc-7e5eff69-6694-4dba-b659-1f22adcbbf83 |             | 1    | default          | available | 85bf0d5b-f0ed-4573-ac1d-a21d61402bf9 |
| 1c410bba-d0f3-4e9c-8c53-4730c4c8d17d | pvc-c1e37c41-0808-43db-a5c7-b9374602b29c |             | 1    | default          | available | 85bf0d5b-f0ed-4573-ac1d-a21d61402bf9 |
| 19b598b6-d7bf-48d9-b99b-a2f5f8b18334 | pvc-0029811b-a4cb-44af-ae8c-4f3bb81f760b |             | 1    | default          | available | 85bf0d5b-f0ed-4573-ac1d-a21d61402bf9 |
| 1279d516-9ac4-43bb-b014-348de3edb672 | pvc-c6251101-94df-44ce-b755-b3ab6b635185 |             | 1    | default          | available | 85bf0d5b-f0ed-4573-ac1d-a21d61402bf9 |
+--------------------------------------+------------------------------------------+-------------+------+------------------+-----------+--------------------------------------+
[root@master-node opensds]#
```

### CODE REVIEW

**Comment by sushanthakumar** [comment]
> **What this PR does / why we need it**:
> Keep GRPC connection alive so we can create/delete/attach/detach volumes in a batch, otherwise GRPC connection would be closed unexpectedly.
> **Which issue this PR fixes** _(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)_: fixes #1153
> 
> **Special notes for your reviewer**:
> Any other PR(s) this PR is dependant on: None

> **Release note**:
> 
> ```
> [root@master-node block]# kubectl create -f multi-pvc.yaml
> storageclass.storage.k8s.io/csi-sc-opensdsplugin-block created
> persistentvolumeclaim/csi-pvc-opensdsplugin-block1 created
> persistentvolumeclaim/csi-pvc-opensdsplugin-block2 created
> persistentvolumeclaim/csi-pvc-opensdsplugin-block3 created
> persistentvolumeclaim/csi-pvc-opensdsplugin-block4 created
> persistentvolumeclaim/csi-pvc-opensdsplugin-block5 created
> persistentvolumeclaim/csi-pvc-opensdsplugin-block6 created
> [root@master-node block]# kubectl get pvc
> NAME                           STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS                 AGE
> csi-pvc-opensdsplugin-block1   Bound    pvc-442b20f3-3112-4b7a-9f72-24cf0306c744   1Gi        RWX            csi-sc-opensdsplugin-block   6s
> csi-pvc-opensdsplugin-block2   Bound    pvc-7e5eff69-6694-4dba-b659-1f22adcbbf83   1Gi        RWX            csi-sc-opensdsplugin-block   6s
> csi-pvc-opensdsplugin-block3   Bound    pvc-c6251101-94df-44ce-b755-b3ab6b635185   1Gi        RWX            csi-sc-opensdsplugin-block   6s
> csi-pvc-opensdsplugin-block4   Bound    pvc-0029811b-a4cb-44af-ae8c-4f3bb81f760b   1Gi        RWX            csi-sc-opensdsplugin-block   6s
> csi-pvc-opensdsplugin-block5   Bound    pvc-c1e37c41-0808-43db-a5c7-b9374602b29c   1Gi        RWX            csi-sc-opensdsplugin-block   6s
> csi-pvc-opensdsplugin-block6   Bound    pvc-0263ef00-7a3c-4c1e-9fce-33c97f9b5738   1Gi        RWX            csi-sc-opensdsplugin-block   6s
> [root@master-node opensds]# osdsctl volume list
> +--------------------------------------+------------------------------------------+-------------+------+------------------+-----------+--------------------------------------+
> | Id                                   | Name                                     | Description | Size | AvailabilityZone | Status    | ProfileId                            |
> +--------------------------------------+------------------------------------------+-------------+------+------------------+-----------+--------------------------------------+
> | dc8cd1bb-bff7-4fb2-911d-d50c77399129 | pvc-442b20f3-3112-4b7a-9f72-24cf0306c744 |             | 1    | default          | available | 85bf0d5b-f0ed-4573-ac1d-a21d61402bf9 |
> | d6f4299b-19a4-46f9-b708-d5c6e641b4c0 | pvc-0263ef00-7a3c-4c1e-9fce-33c97f9b5738 |             | 1    | default          | available | 85bf0d5b-f0ed-4573-ac1d-a21d61402bf9 |
> | 43ce6a63-7aa1-4b51-9de5-f793b90e07f0 | pvc-7e5eff69-6694-4dba-b659-1f22adcbbf83 |             | 1    | default          | available | 85bf0d5b-f0ed-4573-ac1d-a21d61402bf9 |
> | 1c410bba-d0f3-4e9c-8c53-4730c4c8d17d | pvc-c1e37c41-0808-43db-a5c7-b9374602b29c |             | 1    | default          | available | 85bf0d5b-f0ed-4573-ac1d-a21d61402bf9 |
> | 19b598b6-d7bf-48d9-b99b-a2f5f8b18334 | pvc-0029811b-a4cb-44af-ae8c-4f3bb81f760b |             | 1    | default          | available | 85bf0d5b-f0ed-4573-ac1d-a21d61402bf9 |
> | 1279d516-9ac4-43bb-b014-348de3edb672 | pvc-c6251101-94df-44ce-b755-b3ab6b635185 |             | 1    | default          | available | 85bf0d5b-f0ed-4573-ac1d-a21d61402bf9 |
> +--------------------------------------+------------------------------------------+-------------+------+------------------+-----------+--------------------------------------+
> [root@master-node opensds]#
> ```

**Comment by kumarashit** [comment]
One doubt, if a volume creation takes more than 10 sec, will it close connection and recreate connection?

**Comment by ThisIsClark** [comment]
> First of all batch volume creation should be supported from hotpot API side , right?
Hotpot API can create only one volume at once, but nbp can create many pvc to create many volumes by calling hotpot API many times in a very short time.

> Could you please clarify how delayed closing or keeping grpc connection alive for long wil help in batch volume operations?
Before the pr, we used short connection for grpc, which has a bug when handling concurrency, and I wrote the root cause in this [issue1153](https://github.com/opensds/opensds/issues/1153), this is why I choose to use long connection

**Comment by ThisIsClark** [comment]
> One doubt, if a volume creation takes more than 10 sec, will it close connection and recreate connection?

No, the 10 seconds is set for sending pings every 10 seconds if there is no activity to keep the connection alive, so I think if an operation takes more than 10 secs(such as volume creation), the connection would not be closed.

**Comment by kumarashit** [comment]
> 
> 
> > One doubt, if a volume creation takes more than 10 sec, will it close connection and recreate connection?
> 
> No, the 10 seconds is set for sending pings every 10 seconds if there is no activity to keep the connection alive, so I think if an operation takes more than 10 secs(such as volume creation), the connection would not be closed.

Ok

**Comment by kumarashit** [comment]
@ThisIsClark @NajmudheenCT Can we resolve the conversations

**Pull request merged**
