### PR TITLE
Correct code blocks and remove unreached code.

### PR DESCRIPTION
**Pull request by humblec**
Signed-off-by: Humble Chirammal <hchiramm@redhat.com>

**What this PR does / why we need it**:

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
```

### CODE REVIEW

**Comment by xing-yang** [comment]
Hi @humblec, we usually check out from the development branch and make changes and get merged there first.  Before cutting a milestone or release, we'll merge changes from development branch to master.  Do you mind submit this change from the development branch instead?  By the way, I forgot to check this in your other PR, but that's okay as that one only involves doc changes.

**Comment by humblec** [comment]
Sure @xing-yang , let me do it on development branch.. thanks !

**Comment by xing-yang** [comment]
@humblec Looks like the destination branch is still the master?  The PR should be merged into development branch first.  Thanks.

**Comment by xing-yang** [comment]
Oh, I see you have closed it again.

**Pull request closed without merging**
