### PR TITLE
Add ceph driver

### PR DESCRIPTION
**Pull request by xxwjj**
Add ceph driver

### CODE REVIEW

**Comment by leonwanghui** [comment]
@xxwjj Hi Jerry, I noticed that your PR didn't pass the CI, and the errors are as followed:

```
The command "eval go get -t -v ./... " failed. Retrying, 2 of 3.
github.com/ceph/go-ceph/rados
# github.com/ceph/go-ceph/rados
../../ceph/go-ceph/rados/conn.go:5:29: fatal error: rados/librados.h: No such file or directory
 // #include <rados/librados.h>
                             ^
compilation terminated.
```
If I get it right, perhaps the problem is that it didn't install some dependencies of go-ceph package during building the CI, so I suggest you add some installation steps in ```.travis.yml```, then it can drag some packages before building process.

Here is some [tips](https://github.com/ceph/go-ceph/blob/master/.travis.yml) in go-ceph project, hope you can gain some inspiration from it.

**Comment by leonwanghui** [comment]
@xxwjj Hi, I am quite impressed by what you have done, but it would look better if you can add some unit tests. At the same time, I will update travis CI file to add testing validation.

**Comment by xxwjj** [comment]
@leonwanghui  ok , but it will take some time

**Comment by leonwanghui** [comment]
Just take your time : )

**Comment by leonwanghui** [comment]
@xxwjj I'm a bit confused about the outputs below:
```
=== RUN   TestCreateVolume
2017/08/16 10:42:56 [Info] Create volume success, dls = &{dd098495-4269-4e23-a9f1-91b49211d08e volume001  1 ceph}
2017/08/16 10:42:56 [Error] Connect ceph error.
2017/08/16 10:42:56 [Error] Connect ceph error.
--- PASS: TestCreateVolume (0.00s)
=== RUN   TestGetVolume
2017/08/16 10:42:56 [Info] Get volume success, dls = &{7ee11866-1f40-4f3c-b093-7a3684523a19 volume001  1 }
2017/08/16 10:42:56 [Error] When get image: RBD image not found
2017/08/16 10:42:56 [Error] When get volume: RBD image not found
```
Do you know the reason why it passed the testing work even if some errors occur?

**Comment by xxwjj** [comment]
@leonwanghui This is because I tested the exception branches, Those error info the printed by ceph driver,  when i create a exception conditions.

**Comment by leonwanghui** [comment]
Ok, thanks!

**Pull request merged**
