### PR TITLE
Submitting the dashboard code

### PR DESCRIPTION
**Pull request by jimccfun**
**What this PR does / why we need it**:

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
```

### CODE REVIEW

**Comment by xing-yang** [comment]
Why isn't this merged into development branch first before merging into master?  Please also fill out the "What this PR does" section.  Thanks.

**Comment by xing-yang** [comment]
This PR contains lots of changes not really modified by the PR submitter.

**Comment by stmcginnis** [comment]
I would like to see all of the commits squashed, the PR targeted to the development branch, and the PR description filled out.

**Comment by wisererik** [comment]
All the commits should be squashed into one commit

**Pull request closed without merging**
