### PR TITLE
Add storage pool feature to ceph

### PR DESCRIPTION
**Pull request by xxwjj**
Due to the ceph plugin do not support StoragePool feature , we created ceph image use default pool(rbd) before.

So I implment it.

### CODE REVIEW

**Comment by leonwanghui** [comment]
@xxwjj  Hi Jerry, glad to see you have implemented it, but there is something confusing in this patch:
1. According to the ```StoragePoolSpec``` defined in opensds api, I think you missed a field called ```parameter```  which contains all storage features (such as replica number, IOPS and so on) of this pool. And IMO it plays a very important role in storage discovery process, because those features are basics of policy-based orchestration function.
2. After reading your code, I have been wondering if it's better for every function to return a pointer to that structure. Because I found that every structure returned contains a lot of field and it could waste a lot of spaces.

Just my 2 cents :p

**Comment by xxwjj** [comment]
@leonwanghui hi,leonwanghui,great suggestions. But there is problem i think we need to disscuss on next weekly meeting.Because of the cpeh is  a unified, distributed storage system ,some attributes are different from traditional storage pools. such as IOPS,bandwith etc. and these paramter is very important for scheduling. You can see the detail information 
 about the ceph storage pool [here](http://docs.ceph.com/docs/master/rados/operations/pools/)

**Comment by leonwanghui** [comment]
@xxwjj Sorry for replying to you up to now. I noticed that there is something wrong with OpenSDS package dependencies currently, and I have pushed a patch [#64](https://github.com/opensds/opensds/pull/63) to solve this problem. Anyway, what we expect is to find a stable and extensible way to avoid all hidden dangers, rather than fixing bugs after they occur. So I will attach this topic to the next meeting and we could have a disccusion then.

BTW, from your latest patch, there is some exec command (such as ```execCmd("ceph df")```) which could need some packages before building work. So can you have a check and make sure if there are some missing configuration at ```travis.yml``` file?

**Comment by xxwjj** [comment]
@leonwanghui 

    yeah, I agree with you, we should discuess it on next weekly meeting, and  find the root cause.But there is a [issue ](https://github.com/coreos/etcd/issues/8524)in etcd may be some reason for it.

    Due to the ceph api interface provided by libraods librbd is so poor, so I can only get more information by ceph command.The travis CI is just for building and Unite test right now, so there is nothing we need add to travis.

**Comment by leonwanghui** [comment]
Since this patch has conflict with PR [#68](https://github.com/opensds/opensds/pull/68), it will be closed now.

**Pull request closed without merging**
