### PR TITLE
Manage opensds dependency packages through dep tool

### PR DESCRIPTION
**Pull request by leonwanghui**
## Motivation
As we know, opensds controller project is light-weighted because it has no external-dependencies, which means opensds needs to manage all dependencies itself. But for now this project didn't do anything to manage these packages.
## Solution
To solve this problem, I found a popular Go dependency management tool called [dep](https://github.com/golang/dep), and after some experiments I think it can reduce a lot of complicated work for managing dependency packages through this tool.

Here are some outputs when using this tool:
```
krej@krej-Lenovo-IdeaPad-Y470:~/gopath/src/github.com/opensds/opensds$ dep status
PROJECT                            CONSTRAINT     VERSION        REVISION  LATEST   PKGS USED
github.com/asaskevich/govalidator  *              v6             4918b99   4918b99  1   
github.com/astaxie/beego           ^1.9.0         v1.9.0         d96289a   d96289a  9   
github.com/bouk/monkey             branch master  branch master  b96e337   b96e337  1   
github.com/ceph/go-ceph            branch master  branch master  81e4191   81e4191  2   
github.com/coreos/etcd             ^3.2.7         v3.2.7         bb66589   bb66589  5   
github.com/go-openapi/errors       branch master  branch master  03cfca6   03cfca6  1   
github.com/go-openapi/runtime      branch master  branch master  bf2ff8f   bf2ff8f  2   
github.com/go-openapi/strfmt       branch master  branch master  610b6ca   610b6ca  1   
github.com/go-openapi/swag         branch master  branch master  f3f9494   f3f9494  1   
github.com/go-sql-driver/mysql     ^1.3.0         v1.3           a0583e0   a0583e0  1   
github.com/golang/protobuf         branch master  branch master  17ce142   17ce142  5   
github.com/mailru/easyjson         *              branch master  2a92e67   2a92e67  3   
github.com/mitchellh/mapstructure  *              branch master  d0303fe   d0303fe  1   
github.com/satori/go.uuid          ^1.1.0         v1.1.0         879c588   879c588  1   
golang.org/x/net                   branch master  branch master  66aacef   66aacef  8   
golang.org/x/text                  *              branch master  bd91bbf   bd91bbf  9   
google.golang.org/genproto         *              branch master  ee236bd   ee236bd  1   
google.golang.org/grpc             ^1.6.0         v1.6.0         f92cdcd   f92cdcd  15  
gopkg.in/mgo.v2                    *              branch v2      3f83fa5   3f83fa5  2   
gopkg.in/yaml.v2                   *              branch v2      eb3733d   eb3733d  1 
```
As you can see, ```dep``` can not only automatically install the packages but manage their version. That would make it much easier for this project to keep its dependencies in an orderly way.

What do think?

### CODE REVIEW

**Comment by edisonxiang** [comment]
what about another tool "GoDep"?
https://github.com/tools/godep

**Comment by leonwanghui** [comment]
@edisonxiang Yeah, I noticed that, but I didn't have enough time to evaluate both. So I wish someone could finish it so that we can find the better one.

**Comment by edisonxiang** [comment]
@leonwanghui yeah, understood, please refer to 
https://github.com/kubernetes/kubernetes/blob/master/Godeps/Godeps.json

**Comment by leonwanghui** [comment]
This patch has conflict with PR [#67](https://github.com/opensds/opensds/pull/67), so it will be closed.

**Pull request closed without merging**
